import { randomUUID } from "node:crypto";
import type { Job } from "@/lib/types";
import { dedupeKey } from "@/lib/dedupe";

/** Erfundene Beispielstellen für den lokalen Demo-Modus. Firmen sind fiktiv. */
export function demoJobs(): Job[] {
  const base = (p: Partial<Job> & Pick<Job, "firma" | "titel">): Job => ({
    id: randomUUID(),
    quelle: "Demo",
    url: "https://example.com/stelle",
    ort: null,
    pensum: null,
    startdatum: null,
    beschreibung: null,
    kontakt: null,
    email: null,
    bewerbungsweg: "unklar",
    portal_url: null,
    firma_website: null,
    score: 50,
    kategorie: "Sonstiges",
    gruende: [],
    red_flags: [],
    scoring_status: "fertig",
    scoring_fehler: null,
    dedupe_key: dedupeKey(p.firma, p.titel),
    quellen: ["Demo"],
    erstellt_am: new Date().toISOString(),
    ...p,
  });
  return [
    base({
      firma: "Beispiel Filmproduktion AG",
      titel: "Kamera-Trainee / 2nd AC (80-100%)",
      ort: "Basel",
      pensum: "80-100%",
      startdatum: "Januar 2027",
      quelle: "jobs.ch (Alert)",
      score: 91,
      kategorie: "Kamera-Department",
      gruende: ["Direkter Einstieg ins Kamera-Department", "Commercials und Spielfilm", "Region Basel"],
      red_flags: [],
      kontakt: "Anna Muster",
      email: "jobs@example.com",
      bewerbungsweg: "email",
      beschreibung:
        "Wir suchen für unsere Werbe- und Spielfilmproduktionen eine motivierte Person als Kamera-Trainee. Du unterstützt 1st AC und DoP am Set, pflegst das Kamera-Equipment und lernst den Alltag im Kamera-Department kennen.\n\nDein Profil: Erfahrung mit Cinema-Kameras, Interesse an Optiken und Licht, Führerausweis B.\n\nBewerbung an Anna Muster, jobs@example.com.",
    }),
    base({
      firma: "Lichtblick Rental GmbH",
      titel: "Mitarbeiter:in Kameraverleih",
      ort: "Zürich",
      pensum: "100%",
      startdatum: "per sofort",
      quelle: "LinkedIn (Alert)",
      score: 74,
      kategorie: "Rental/Technik",
      gruende: ["RED und Cine-Optiken im Alltag", "Kontakt zu vielen Produktionen"],
      red_flags: ["Start per sofort (vor Januar 2027)"],
      bewerbungsweg: "portal",
      portal_url: "https://example.com/portal",
      beschreibung: "Prüfen, konfigurieren und ausgeben von Kamerapaketen. Beratung von Kameraleuten.",
    }),
    base({
      firma: "Nordlicht Studios",
      titel: "Produktionsassistenz Commercial",
      ort: "Zürich",
      pensum: "100%",
      startdatum: "Frühling 2027",
      quelle: "jobup.ch (Alert)",
      score: 68,
      kategorie: "Produktionsassistenz",
      gruende: ["Professionelle Sets", "Commercial-Fokus"],
      red_flags: ["Pendeln Sissach–Zürich"],
      bewerbungsweg: "email",
      email: "hello@example.com",
      beschreibung: "Unterstützung der Producer bei Planung und Durchführung von Werbedrehs.",
    }),
    base({
      firma: "Agentur Flimmer",
      titel: "Videograf:in Social Media",
      ort: "Bern",
      pensum: "60%",
      startdatum: "Januar 2027",
      quelle: "Indeed (Alert)",
      score: 44,
      kategorie: "Agentur/Brand Content",
      gruende: ["Eigene Drehs", "Kundenkontakt"],
      red_flags: ["Pensum 60%", "Eher Social-Content als Film"],
      bewerbungsweg: "unklar",
      beschreibung: "Konzeption und Produktion von Kurzvideos für Instagram und TikTok.",
    }),
    base({
      firma: "Grade Lab AG",
      titel: "Praktikum Postproduktion & Color",
      ort: "Basel",
      pensum: "100%",
      startdatum: "Februar 2027",
      quelle: "Karriereseite: Grade Lab",
      score: 63,
      kategorie: "Post/Color",
      gruende: ["DaVinci Resolve Studio", "Color Management"],
      red_flags: [],
      bewerbungsweg: "email",
      email: "praktikum@example.com",
      beschreibung: "6-monatiges Praktikum im Color-Department, Assistenz der Coloristen.",
    }),
  ];
}
